# This is a basic workflow to help you get started with Actions

name: LABA5TESTS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        ops: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.ops}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: TEST_RUN
        run: python -m unittest geometric_tests.py
