name: Run Unit Tests

on: [push]

jobs:
  build:
  
    name: Unit Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up py ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: python Running-tests.py
