name: CI tests (lab5)

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Rectangle
        run: python -m unittest RectangleTest.py
      - name: Circle  
        run: python -m unittest CircleTest.py
      - name: Square
        run: python -m unittest squareTest.py
      - name: Triangle
        run: python -m unittest triangleTest.py

