name: "Tests"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_one:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: setup Python
         uses: actions/setup-python@v4
         with:
           python-version: "3.11"
       - name: Run rectangle_test.py
         run: python3 -m unittest rectangle_test.py
       - name: Run triangle_test.py
         run: python3 -m unittest triangle_test.py
       - name: Run circle_test.py
         run: python3 -m unittest circle_test.py
       - name: Run square_test.py
         run: python3 -m unittest square_test.py

  test_two:
     runs-on: windows-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: setup Python
         uses: actions/setup-python@v4
         with:
           python-version: "3.11"
       - name: Run rectangle_test.py
         run: python3 -m unittest rectangle_test.py
       - name: Run triangle_test.py
         run: python3 -m unittest triangle_test.py
       - name: Run circle_test.py
         run: python3 -m unittest circle_test.py
       - name: Run square_test.py
         run: python3 -m unittest square_test.py
