name: CI/CD
on:
  push:
    branches:
      - cicd_410610
  pull_request:
    branches:
      - cicd_410610
permissions:
  contents: read
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        
        with:
          python-version: "3.12"
          architecture: x64
      - name: tests run
        run: python -m unittest
  windows-latest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        
        with:
          python-version: "3.12"
          architecture: x64
      - name: tests run
        run: python -m unittest
